version: '3.4'

networks:
  phoneshopapi:

services:
  phoneshopdb:
    container_name: phone-shop-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1432:1432
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TGluongkhoatruonganh123456!@#123
    networks:
      - phoneshopapi
  phoneshopapi.apigateway:
    container_name: phone-shop-api-api-gateway
    image: ${DOCKER_REGISTRY-}phone-shop-api.api-gateway
    build:
      context: .
      dockerfile: PhoneShopApi.ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    networks:
      - phoneshopapi
  phoneshopapi.product:
    container_name: phone-shop-api-product
    image: ${DOCKER_REGISTRY-}phone-shop-api.product
    build:
      context: .
      dockerfile: PhoneShopApi.Product/Dockerfile
    ports:
      - "19001:8080"
    depends_on:
      - phoneshopdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DB_HOST=phoneshopdb
      - DB_NAME=PhoneShopDb
      - DB_SA_PASSWORD=TGluongkhoatruonganh123456!@#123
    networks:
      - phoneshopapi

  phoneshopapi.auth:
    container_name: phone-shop-api.auth
    image: ${DOCKER_REGISTRY-}phone-shop-api.auth
    build:
      context: .
      dockerfile: PhoneShopApi.Auth/Dockerfile
    ports:
      - "19002:8080"
    depends_on:
      - phoneshopdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DB_HOST=phoneshopdb
      - DB_NAME=PhoneShopDb
      - DB_SA_PASSWORD=TGluongkhoatruonganh123456!@#123
    networks:
      - phoneshopapi


  phoneshopapi.ordering:
    container_name: phone-shop-api.ordering
    image: ${DOCKER_REGISTRY-}phone-shop-api.ordering
    build:
      context: .
      dockerfile: PhoneShopApi.Ordering/Dockerfile
    ports:
      - "19003:8080"
    depends_on:
      - phoneshopdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DB_HOST=phoneshopdb
      - DB_NAME=PhoneShopDb
      - DB_SA_PASSWORD=TGluongkhoatruonganh123456!@#123
    networks:
      - phoneshopapi


  phoneshop-store:
    container_name: phone-shop-store
    build: ./store
    ports:
      - "3002:3000"
    networks:
      - phoneshopapi
    volumes:
      - ./store:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  


