name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:
  
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker login
      env:
        USER: ${{ secrets.DOCKERHUB_USERNAME }}
        PASS: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./LearnSmartCoding.API/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/phoneshopapi:latest, ${{ secrets.DOCKERHUB_USERNAME }}/phoneshopapi:${{ github.run_number }}
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
